<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Web service function definitions for Modern Commerce.
 *
 * @package    local_moderncommerce
 * @copyright  2025 Adebare Showemimo | adebareshowemimo@gmail.com | support@agunfoninteractivity.com | www.agunfoninteractivity.com
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_moderncommerce_get_catalog' => [
        'classname'     => 'local_moderncommerce\external\catalog\get_catalog',
        'methodname'    => 'execute',
        'description'   => 'Get the deduplicated public Modern Commerce catalog dataset for React catalog pages.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => false,
    ],
    'local_moderncommerce_get_bundle_details' => [
        'classname'     => 'local_moderncommerce\external\bundles\get_bundle_details',
        'methodname'    => 'execute',
        'description'   => 'Get a public Modern Commerce bundle or program details dataset for React pages.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => false,
    ],
    'local_moderncommerce_get_course_details' => [
        'classname'     => 'local_moderncommerce\external\courses\get_course_details',
        'methodname'    => 'execute',
        'description'   => 'Get a public Modern Commerce course details dataset for React pages.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => false,
    ],
    'local_moderncommerce_reviews_get_overview' => [
        'classname'     => 'local_moderncommerce\external\reviews\review_external',
        'methodname'    => 'get_overview',
        'description'   => 'Get the Modern Commerce course reviews admin overview.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managereviews',
        'loginrequired' => true,
    ],
    'local_moderncommerce_reviews_list_courses' => [
        'classname'     => 'local_moderncommerce\external\reviews\review_external',
        'methodname'    => 'list_courses',
        'description'   => 'List courses with Modern Commerce review statistics.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managereviews',
        'loginrequired' => true,
    ],
    'local_moderncommerce_reviews_list_reviews' => [
        'classname'     => 'local_moderncommerce\external\reviews\review_external',
        'methodname'    => 'list_reviews',
        'description'   => 'List Modern Commerce course reviews for moderation.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managereviews',
        'loginrequired' => true,
    ],
    'local_moderncommerce_reviews_moderate' => [
        'classname'     => 'local_moderncommerce\external\reviews\review_external',
        'methodname'    => 'moderate',
        'description'   => 'Hide, show, or delete a Modern Commerce course review.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managereviews',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_course_reviews' => [
        'classname'     => 'local_moderncommerce\external\reviews\review_external',
        'methodname'    => 'get_course_reviews',
        'description'   => 'Get public visible Modern Commerce course reviews.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewreviews',
        'loginrequired' => false,
    ],
    'local_moderncommerce_submit_course_review' => [
        'classname'     => 'local_moderncommerce\external\reviews\review_external',
        'methodname'    => 'submit_review',
        'description'   => 'Submit a Modern Commerce course review for the current learner.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:submitreview',
        'loginrequired' => true,
    ],
    'local_moderncommerce_set_course_review_reaction' => [
        'classname'     => 'local_moderncommerce\external\reviews\review_external',
        'methodname'    => 'set_reaction',
        'description'   => 'Set or toggle a Modern Commerce course review reaction.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewreviews',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_cart' => [
        'classname'     => 'local_moderncommerce\external\cart\get_cart',
        'methodname'    => 'execute',
        'description'   => 'Get the current buyer Modern Commerce cart dataset.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:purchase',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_cart_dropdown' => [
        'classname'     => 'local_moderncommerce\external\cart\get_dropdown',
        'methodname'    => 'execute',
        'description'   => 'Render the current buyer Modern Commerce cart dropdown HTML.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:purchase',
        'loginrequired' => true,
    ],
    'local_moderncommerce_update_cart' => [
        'classname'     => 'local_moderncommerce\external\cart\update_cart',
        'methodname'    => 'execute',
        'description'   => 'Update the current buyer Modern Commerce cart or coupon state.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:purchase',
        'loginrequired' => true,
    ],
    'local_moderncommerce_start_checkout' => [
        'classname'     => 'local_moderncommerce\external\checkout\start_checkout',
        'methodname'    => 'execute',
        'description'   => 'Start Modern Commerce checkout for the current buyer.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:purchase',
        'loginrequired' => true,
    ],
    'local_moderncommerce_place_order' => [
        'classname'     => 'local_moderncommerce\external\checkout\place_order',
        'methodname'    => 'execute',
        'description'   => 'Place or continue a Modern Commerce checkout order.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:purchase',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_learner_dashboard' => [
        'classname'     => 'local_moderncommerce\external\learner\get_dashboard',
        'methodname'    => 'execute',
        'description'   => 'Get the current learner Modern Commerce dashboard dataset.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => true,
    ],
    'local_moderncommerce_list_learner_courses' => [
        'classname'     => 'local_moderncommerce\external\learner\list_courses',
        'methodname'    => 'execute',
        'description'   => 'List the current learner Modern Commerce course access dataset.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => true,
    ],
    'local_moderncommerce_list_learner_certificates' => [
        'classname'     => 'local_moderncommerce\external\learner\list_certificates',
        'methodname'    => 'execute',
        'description'   => 'List the current learner Modern Commerce certificate records.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => true,
    ],
    'local_moderncommerce_list_learner_grades' => [
        'classname'     => 'local_moderncommerce\external\learner\list_grades',
        'methodname'    => 'execute',
        'description'   => 'List the current learner Moodle grade overview data for Modern Commerce.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => true,
    ],
    'local_moderncommerce_list_learner_orders' => [
        'classname'     => 'local_moderncommerce\external\learner\list_orders',
        'methodname'    => 'execute',
        'description'   => 'List the current learner Modern Commerce order history dataset.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewownorders',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_learner_order' => [
        'classname'     => 'local_moderncommerce\external\learner\get_order',
        'methodname'    => 'execute',
        'description'   => 'Get one Modern Commerce learner order detail dataset.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewownorders',
        'loginrequired' => true,
    ],
    'local_moderncommerce_cancel_learner_order' => [
        'classname'     => 'local_moderncommerce\external\learner\cancel_order',
        'methodname'    => 'execute',
        'description'   => 'Cancel a pending Modern Commerce buyer order.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewownorders',
        'loginrequired' => true,
    ],
    'local_moderncommerce_list_learner_wishlist' => [
        'classname'     => 'local_moderncommerce\external\learner\list_wishlist',
        'methodname'    => 'execute',
        'description'   => 'List the current learner Modern Commerce wishlist.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => true,
    ],
    'local_moderncommerce_update_learner_wishlist' => [
        'classname'     => 'local_moderncommerce\external\learner\update_wishlist',
        'methodname'    => 'execute',
        'description'   => 'Add, remove, or move Modern Commerce wishlist items.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_learner_subscription' => [
        'classname'     => 'local_moderncommerce\external\learner\get_subscription',
        'methodname'    => 'execute',
        'description'   => 'Get the current learner Modern Commerce subscription summary dataset.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_learner_subscription_access' => [
        'classname'     => 'local_moderncommerce\external\learner\get_subscription_access',
        'methodname'    => 'execute',
        'description'   => 'Get the current learner Modern Commerce subscription access dataset.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_learner_product_access' => [
        'classname'     => 'local_moderncommerce\external\learner\get_product_access',
        'methodname'    => 'execute',
        'description'   => 'Get the current learner access details for an owned bundle or program.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_learner_profile' => [
        'classname'     => 'local_moderncommerce\external\learner\get_profile',
        'methodname'    => 'execute',
        'description'   => 'Get the current learner profile data for the Modern Commerce profile page.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => true,
    ],
    'local_moderncommerce_save_learner_profile' => [
        'classname'     => 'local_moderncommerce\external\learner\save_profile',
        'methodname'    => 'execute',
        'description'   => 'Save the current learner profile fields for the Modern Commerce profile page.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'moodle/user:editownprofile',
        'loginrequired' => true,
    ],
    'local_moderncommerce_save_learner_profile_picture' => [
        'classname'     => 'local_moderncommerce\external\learner\save_profile_picture',
        'methodname'    => 'execute',
        'description'   => 'Save or remove the current learner profile image.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'moodle/user:editownprofile',
        'loginrequired' => true,
    ],
    'local_moderncommerce_search_courses' => [
        'classname'     => 'local_moderncommerce\external\courses\search_courses',
        'methodname'    => 'execute',
        'description'   => 'Search Moodle courses for Modern Commerce admin typeahead selectors.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_list_products' => [
        'classname'     => 'local_moderncommerce\external\products\list_products',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce products with pricing, inventory, and sales summary data.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_save_product' => [
        'classname'     => 'local_moderncommerce\external\products\save_product',
        'methodname'    => 'execute',
        'description'   => 'Create or update a Modern Commerce product, regular price, inventory, and primary category.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_list_categories' => [
        'classname'     => 'local_moderncommerce\external\categories\list_categories',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce product categories with product counts.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecategories',
        'loginrequired' => true,
    ],
    'local_moderncommerce_save_category' => [
        'classname'     => 'local_moderncommerce\external\categories\save_category',
        'methodname'    => 'execute',
        'description'   => 'Create or update a Modern Commerce product category.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecategories',
        'loginrequired' => true,
    ],
    'local_moderncommerce_delete_category' => [
        'classname'     => 'local_moderncommerce\external\categories\delete_category',
        'methodname'    => 'execute',
        'description'   => 'Delete a Modern Commerce product category.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecategories',
        'loginrequired' => true,
    ],
    'local_moderncommerce_reorder_categories' => [
        'classname'     => 'local_moderncommerce\external\categories\reorder_categories',
        'methodname'    => 'execute',
        'description'   => 'Persist a drag-and-drop display order for Modern Commerce product categories.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecategories',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_product' => [
        'classname'     => 'local_moderncommerce\external\products\get_product',
        'methodname'    => 'execute',
        'description'   => 'Get one Modern Commerce product with editable pricing and inventory fields.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_toggle_product' => [
        'classname'     => 'local_moderncommerce\external\products\toggle_product',
        'methodname'    => 'execute',
        'description'   => 'Quickly update a Modern Commerce product flag, status, or price enabled state.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_archive_product' => [
        'classname'     => 'local_moderncommerce\external\products\archive_product',
        'methodname'    => 'execute',
        'description'   => 'Archive a Modern Commerce product so it is no longer visible for sale.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_list_product_prices' => [
        'classname'     => 'local_moderncommerce\external\pricing\list_prices',
        'methodname'    => 'execute',
        'description'   => 'List normalized Modern Commerce product price rows.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_save_product_price' => [
        'classname'     => 'local_moderncommerce\external\pricing\save_price',
        'methodname'    => 'execute',
        'description'   => 'Create or update a normalized Modern Commerce product price row.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_archive_product_price' => [
        'classname'     => 'local_moderncommerce\external\pricing\archive_price',
        'methodname'    => 'execute',
        'description'   => 'Archive a Modern Commerce product price row while preserving history.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_list_coupons' => [
        'classname'     => 'local_moderncommerce\external\coupons\list_coupons',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce coupons with runtime status and usage data.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecoupons',
        'loginrequired' => true,
    ],
    'local_moderncommerce_save_coupon' => [
        'classname'     => 'local_moderncommerce\external\coupons\save_coupon',
        'methodname'    => 'execute',
        'description'   => 'Create or update a Modern Commerce coupon.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecoupons',
        'loginrequired' => true,
    ],
    'local_moderncommerce_check_coupon_code' => [
        'classname'     => 'local_moderncommerce\external\coupons\check_code',
        'methodname'    => 'execute',
        'description'   => 'Check whether a Modern Commerce coupon code is already in use.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecoupons',
        'loginrequired' => true,
    ],
    'local_moderncommerce_archive_coupon' => [
        'classname'     => 'local_moderncommerce\external\coupons\archive_coupon',
        'methodname'    => 'execute',
        'description'   => 'Archive a Modern Commerce coupon while preserving redemption history.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecoupons',
        'loginrequired' => true,
    ],
    'local_moderncommerce_list_coupon_targets' => [
        'classname'     => 'local_moderncommerce\external\coupons\list_targets',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce coupon applicability targets.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecoupons',
        'loginrequired' => true,
    ],
    'local_moderncommerce_save_coupon_target' => [
        'classname'     => 'local_moderncommerce\external\coupons\save_target',
        'methodname'    => 'execute',
        'description'   => 'Create or update a Modern Commerce coupon applicability target.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecoupons',
        'loginrequired' => true,
    ],
    'local_moderncommerce_delete_coupon_target' => [
        'classname'     => 'local_moderncommerce\external\coupons\delete_target',
        'methodname'    => 'execute',
        'description'   => 'Delete a Modern Commerce coupon applicability target.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecoupons',
        'loginrequired' => true,
    ],
    'local_moderncommerce_search_coupon_target_options' => [
        'classname'     => 'local_moderncommerce\external\coupons\search_target_options',
        'methodname'    => 'execute',
        'description'   => 'Search target options for Modern Commerce coupon applicability rules.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecoupons',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_list_orders' => [
        'classname'     => 'local_moderncommerce\external\orders\list_orders',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce orders with status, totals, and summary stats for the admin orders screen.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewallorders',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_order' => [
        'classname'     => 'local_moderncommerce\external\orders\get_order',
        'methodname'    => 'execute',
        'description'   => 'Get one Modern Commerce order with items, payments, refunds, and billing for the admin detail screen.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewallorders',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_list_customers' => [
        'classname'     => 'local_moderncommerce\external\customers\list_customers',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce customers with order and spend summary data.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewallorders',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_customer' => [
        'classname'     => 'local_moderncommerce\external\customers\get_customer',
        'methodname'    => 'execute',
        'description'   => 'Get one Modern Commerce customer with commerce stats, billing snapshot, and order history.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewallorders',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_list_wishlists' => [
        'classname'     => 'local_moderncommerce\external\wishlists\list_wishlists',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce wishlist demand and recent saved-product activity.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewreports',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_update_order_status' => [
        'classname'     => 'local_moderncommerce\external\orders\update_status',
        'methodname'    => 'execute',
        'description'   => 'Change the status of a Modern Commerce order.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:manageorders',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_create_refund' => [
        'classname'     => 'local_moderncommerce\external\orders\create_refund',
        'methodname'    => 'execute',
        'description'   => 'Record a refund for a Modern Commerce order and optionally revoke buyer access.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:processrefunds',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_list_gateways' => [
        'classname'     => 'local_moderncommerce\external\payments\list_gateways',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce payment gateways with readiness and recent activity.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:configuregateways',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_save_gateway' => [
        'classname'     => 'local_moderncommerce\external\payments\save_gateway',
        'methodname'    => 'execute',
        'description'   => 'Create or update a Modern Commerce payment gateway configuration.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:configuregateways',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_webhooks' => [
        'classname'     => 'local_moderncommerce\external\payments\get_webhooks',
        'methodname'    => 'execute',
        'description'   => 'Get Modern Commerce webhook endpoint configuration for each gateway.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:configuregateways',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_list_webhook_events' => [
        'classname'     => 'local_moderncommerce\external\payments\list_webhook_events',
        'methodname'    => 'execute',
        'description'   => 'List recent Modern Commerce webhook events.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:configuregateways',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_list_bundles' => [
        'classname'     => 'local_moderncommerce\external\bundles\list_bundles',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce bundles and programs with course counts and pricing.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_bundle' => [
        'classname'     => 'local_moderncommerce\external\bundles\get_bundle',
        'methodname'    => 'execute',
        'description'   => 'Get one Modern Commerce bundle or program with included courses for the builder.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_save_bundle' => [
        'classname'     => 'local_moderncommerce\external\bundles\save_bundle',
        'methodname'    => 'execute',
        'description'   => 'Create or update a Modern Commerce bundle or program and its included courses.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_archive_bundle' => [
        'classname'     => 'local_moderncommerce\external\bundles\archive_bundle',
        'methodname'    => 'execute',
        'description'   => 'Archive a Modern Commerce bundle or program.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_save_bundle_image' => [
        'classname'     => 'local_moderncommerce\external\bundles\save_bundle_image',
        'methodname'    => 'execute',
        'description'   => 'Upload or remove the image for a Modern Commerce bundle or program.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_list_keys' => [
        'classname'     => 'local_moderncommerce\external\enrollkeys\list_keys',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce enrollment keys with targets, status, and usage.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:generatekeys',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_generate_keys' => [
        'classname'     => 'local_moderncommerce\external\enrollkeys\generate_keys',
        'methodname'    => 'execute',
        'description'   => 'Generate Modern Commerce enrollment keys for a course or product target.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:generatekeys',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_set_key_status' => [
        'classname'     => 'local_moderncommerce\external\enrollkeys\set_key_status',
        'methodname'    => 'execute',
        'description'   => 'Activate, deactivate, or delete a Modern Commerce enrollment key.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:generatekeys',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_list_invoices' => [
        'classname'     => 'local_moderncommerce\external\invoices\list_invoices',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce invoices with customer, totals, and status.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:manageorders',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_invoice' => [
        'classname'     => 'local_moderncommerce\external\invoices\get_invoice',
        'methodname'    => 'execute',
        'description'   => 'Get one Modern Commerce invoice with line items.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:manageorders',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_save_invoice' => [
        'classname'     => 'local_moderncommerce\external\invoices\save_invoice',
        'methodname'    => 'execute',
        'description'   => 'Create or update a Modern Commerce manual invoice and its line items.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:manageorders',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_set_invoice_status' => [
        'classname'     => 'local_moderncommerce\external\invoices\set_invoice_status',
        'methodname'    => 'execute',
        'description'   => 'Change the status of a Modern Commerce invoice or delete it.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:manageorders',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_search_customers' => [
        'classname'     => 'local_moderncommerce\external\invoices\search_customers',
        'methodname'    => 'execute',
        'description'   => 'Search customers for the Modern Commerce invoice editor.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:manageorders',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_report' => [
        'classname'     => 'local_moderncommerce\external\reports\get_report',
        'methodname'    => 'execute',
        'description'   => 'Get Modern Commerce sales, top course, and coupon analytics.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewreports',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_dashboard' => [
        'classname'     => 'local_moderncommerce\external\reports\get_dashboard',
        'methodname'    => 'execute',
        'description'   => 'Get the Modern Commerce admin dashboard KPIs, recent orders, and alerts.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewreports',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_dashboard_charts' => [
        'classname'     => 'local_moderncommerce\external\reports\get_dashboard_charts',
        'methodname'    => 'execute',
        'description'   => 'Get the Modern Commerce admin dashboard analytics chart datasets.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewreports',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_dashboard_layout' => [
        'classname'     => 'local_moderncommerce\external\reports\get_dashboard_layout',
        'methodname'    => 'execute',
        'description'   => 'Get the editable per-admin Modern Commerce dashboard layout (manager).',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewreports',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_save_dashboard_layout' => [
        'classname'     => 'local_moderncommerce\external\reports\save_dashboard_layout',
        'methodname'    => 'execute',
        'description'   => 'Save the per-admin (or site-default) Modern Commerce dashboard layout.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewreports',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_storefront_page' => [
        'classname'     => 'local_moderncommerce\external\storefront\get_storefront_page',
        'methodname'    => 'execute',
        'description'   => 'Get the resolved Modern Commerce storefront widgets grouped by zone.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => false,
    ],
    'local_moderncommerce_get_storefront_gallery' => [
        'classname'     => 'local_moderncommerce\external\storefront\get_storefront_gallery',
        'methodname'    => 'execute',
        'description'   => 'Get the admin-only demo widget gallery (every widget type in every style).',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managestorefront',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_demo_catalog' => [
        'classname'     => 'local_moderncommerce\external\catalog\get_demo_catalog',
        'methodname'    => 'execute',
        'description'   => 'Get fixed demo products for the admin widget gallery product widgets.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managestorefront',
        'loginrequired' => true,
    ],
    'local_moderncommerce_list_widget_presets' => [
        'classname'     => 'local_moderncommerce\external\storefront\list_widget_presets',
        'methodname'    => 'execute',
        'description'   => 'List saved Modern Commerce storefront widget style presets.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managestorefront',
        'loginrequired' => true,
    ],
    'local_moderncommerce_save_widget_preset' => [
        'classname'     => 'local_moderncommerce\external\storefront\save_widget_preset',
        'methodname'    => 'execute',
        'description'   => 'Create or update a Modern Commerce storefront widget style preset.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managestorefront',
        'loginrequired' => true,
    ],
    'local_moderncommerce_delete_widget_preset' => [
        'classname'     => 'local_moderncommerce\external\storefront\delete_widget_preset',
        'methodname'    => 'execute',
        'description'   => 'Delete a Modern Commerce storefront widget style preset.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managestorefront',
        'loginrequired' => true,
    ],
    'local_moderncommerce_newsletter_subscribe' => [
        'classname'     => 'local_moderncommerce\external\newsletter\subscribe',
        'methodname'    => 'execute',
        'description'   => 'Store a Modern Commerce newsletter subscriber.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcatalog',
        'loginrequired' => false,
    ],
    'local_moderncommerce_newsletter_list_subscribers' => [
        'classname'     => 'local_moderncommerce\external\newsletter\admin',
        'methodname'    => 'list_subscribers',
        'description'   => 'List Modern Commerce newsletter subscribers.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewnewsletter',
        'loginrequired' => true,
    ],
    'local_moderncommerce_newsletter_delete_subscriber' => [
        'classname'     => 'local_moderncommerce\external\newsletter\admin',
        'methodname'    => 'delete_subscriber',
        'description'   => 'Delete a Modern Commerce newsletter subscriber.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managenewsletter',
        'loginrequired' => true,
    ],
    'local_moderncommerce_newsletter_export_subscribers' => [
        'classname'     => 'local_moderncommerce\external\newsletter\admin',
        'methodname'    => 'export_subscribers',
        'description'   => 'Export Modern Commerce newsletter subscribers as CSV.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewnewsletter',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_storefront_layout' => [
        'classname'     => 'local_moderncommerce\external\storefront\get_storefront_layout',
        'methodname'    => 'execute',
        'description'   => 'Get the editable Modern Commerce storefront widget layout (Customize drawer).',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managestorefront',
        'loginrequired' => true,
    ],
    'local_moderncommerce_save_storefront_layout' => [
        'classname'     => 'local_moderncommerce\external\storefront\save_storefront_layout',
        'methodname'    => 'execute',
        'description'   => 'Save the Modern Commerce storefront widget layout (zone, order, visibility).',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managestorefront',
        'loginrequired' => true,
    ],
    'local_moderncommerce_toggle_storefront_page' => [
        'classname'     => 'local_moderncommerce\external\storefront\toggle_page',
        'methodname'    => 'execute',
        'description'   => 'Enable or disable an optional Modern Commerce public page.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managestorefront',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_storefront_widget' => [
        'classname'     => 'local_moderncommerce\external\storefront\get_storefront_widget',
        'methodname'    => 'execute',
        'description'   => 'Get one storefront widget settings + field schema for the React editor.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managestorefront',
        'loginrequired' => true,
    ],
    'local_moderncommerce_save_storefront_widget' => [
        'classname'     => 'local_moderncommerce\external\storefront\save_storefront_widget',
        'methodname'    => 'execute',
        'description'   => 'Save one storefront widget settings (and slider slides).',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managestorefront',
        'loginrequired' => true,
    ],
    'local_moderncommerce_add_storefront_widget' => [
        'classname'     => 'local_moderncommerce\external\storefront\add_storefront_widget',
        'methodname'    => 'execute',
        'description'   => 'Create a new Modern Commerce storefront widget in a zone.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managestorefront',
        'loginrequired' => true,
    ],
    'local_moderncommerce_delete_storefront_widget' => [
        'classname'     => 'local_moderncommerce\external\storefront\delete_storefront_widget',
        'methodname'    => 'execute',
        'description'   => 'Delete a Modern Commerce storefront widget.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managestorefront',
        'loginrequired' => true,
    ],
    'local_moderncommerce_upload_slide_image' => [
        'classname'     => 'local_moderncommerce\external\storefront\upload_slide_image',
        'methodname'    => 'execute',
        'description'   => 'Store an uploaded hero-slide image and return its public URL.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managestorefront',
        'loginrequired' => true,
    ],
    'local_moderncommerce_validate_key' => [
        'classname'     => 'local_moderncommerce\external\redeem\validate_key',
        'methodname'    => 'execute',
        'description'   => 'Validate a Modern Commerce enrollment key and preview the courses it grants.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:redeemkey',
        'loginrequired' => true,
    ],
    'local_moderncommerce_redeem_key' => [
        'classname'     => 'local_moderncommerce\external\redeem\redeem_key',
        'methodname'    => 'execute',
        'description'   => 'Redeem a Modern Commerce enrollment key and enrol the buyer in granted courses.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:redeemkey',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_list_emails' => [
        'classname'     => 'local_moderncommerce\external\emails\list_emails',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce email notification types with enabled state.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_email' => [
        'classname'     => 'local_moderncommerce\external\emails\get_email',
        'methodname'    => 'execute',
        'description'   => 'Get one Modern Commerce email notification setting with placeholders.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_save_email' => [
        'classname'     => 'local_moderncommerce\external\emails\save_email',
        'methodname'    => 'execute',
        'description'   => 'Save one Modern Commerce email notification setting.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:manageemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_email_get_metadata' => [
        'classname'     => 'local_moderncommerce\external\email_templates\admin_external',
        'methodname'    => 'get_metadata',
        'description'   => 'Get the placeholder palette and filters for Modern Commerce email templates.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_email_list_templates' => [
        'classname'     => 'local_moderncommerce\external\email_templates\admin_external',
        'methodname'    => 'list_templates',
        'description'   => 'List Modern Commerce email templates.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_email_get_template' => [
        'classname'     => 'local_moderncommerce\external\email_templates\admin_external',
        'methodname'    => 'get_template',
        'description'   => 'Get one Modern Commerce email template.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_email_save_template' => [
        'classname'     => 'local_moderncommerce\external\email_templates\admin_external',
        'methodname'    => 'save_template',
        'description'   => 'Create or update one Modern Commerce email template.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:manageemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_email_delete_template' => [
        'classname'     => 'local_moderncommerce\external\email_templates\admin_external',
        'methodname'    => 'delete_template',
        'description'   => 'Delete one custom Modern Commerce email template.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:manageemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_email_clone_template' => [
        'classname'     => 'local_moderncommerce\external\email_templates\admin_external',
        'methodname'    => 'clone_template',
        'description'   => 'Clone one Modern Commerce email template.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:manageemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_email_preview_template' => [
        'classname'     => 'local_moderncommerce\external\email_templates\admin_external',
        'methodname'    => 'preview_template',
        'description'   => 'Preview one Modern Commerce email template through the global shell.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_email_get_shell' => [
        'classname'     => 'local_moderncommerce\external\email_templates\admin_external',
        'methodname'    => 'get_shell',
        'description'   => 'Get the Modern Commerce global email shell.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_email_save_shell' => [
        'classname'     => 'local_moderncommerce\external\email_templates\admin_external',
        'methodname'    => 'save_shell',
        'description'   => 'Save the Modern Commerce global email shell.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:manageemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_email_preview_shell' => [
        'classname'     => 'local_moderncommerce\external\email_templates\admin_external',
        'methodname'    => 'preview_shell',
        'description'   => 'Preview the Modern Commerce global email shell.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_email_reset_shell' => [
        'classname'     => 'local_moderncommerce\external\email_templates\admin_external',
        'methodname'    => 'reset_shell',
        'description'   => 'Reset the Modern Commerce global email shell.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:manageemailtemplates',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_list_payment_events' => [
        'classname'     => 'local_moderncommerce\external\ledgers\list_payment_events',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce payment events for the admin ledger.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:configuregateways',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_list_webhook_ledger' => [
        'classname'     => 'local_moderncommerce\external\ledgers\list_webhook_events',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce webhook events for the admin ledger.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:configuregateways',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_list_audit_log' => [
        'classname'     => 'local_moderncommerce\external\ledgers\list_audit_log',
        'methodname'    => 'execute',
        'description'   => 'List Modern Commerce audit log entries for the admin ledger.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewauditlog',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_course_features' => [
        'classname'     => 'local_moderncommerce\external\courses\get_course_features',
        'methodname'    => 'execute',
        'description'   => 'Get a Modern Commerce course advanced/merchandising metadata.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_save_course_features' => [
        'classname'     => 'local_moderncommerce\external\courses\save_course_features',
        'methodname'    => 'execute',
        'description'   => 'Save a Modern Commerce course advanced/merchandising metadata.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_bundle_features' => [
        'classname'     => 'local_moderncommerce\external\bundles\get_bundle_features',
        'methodname'    => 'execute',
        'description'   => 'Get a Modern Commerce bundle advanced/merchandising metadata.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_save_bundle_features' => [
        'classname'     => 'local_moderncommerce\external\bundles\save_bundle_features',
        'methodname'    => 'execute',
        'description'   => 'Save a Modern Commerce bundle advanced/merchandising metadata.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecourses',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_settings' => [
        'classname'     => 'local_moderncommerce\external\settings\get_settings',
        'methodname'    => 'execute',
        'description'   => 'Get the Modern Commerce commerce settings.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managesettings',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_save_settings' => [
        'classname'     => 'local_moderncommerce\external\settings\save_settings',
        'methodname'    => 'execute',
        'description'   => 'Validate and save the Modern Commerce commerce settings.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managesettings',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_notifications' => [
        'classname'     => 'local_moderncommerce\external\notifications\get_notifications',
        'methodname'    => 'execute',
        'description'   => 'Get the Modern Notify delivery dashboard dataset for the Modern Commerce shell.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managenotifications',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_save_notification_settings' => [
        'classname'     => 'local_moderncommerce\external\notifications\save_settings',
        'methodname'    => 'execute',
        'description'   => 'Save Modern Notify channel settings from the Modern Commerce shell.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managenotifications',
        'loginrequired' => true,
    ],
    'local_moderncommerce_submit_contact' => [
        'classname'     => 'local_moderncommerce\external\contacts\submit',
        'methodname'    => 'execute',
        'description'   => 'Submit a contact form entry and queue the notification emails.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => '',
        'loginrequired' => false,
    ],
    'local_moderncommerce_get_contacts' => [
        'classname'     => 'local_moderncommerce\external\contacts\admin',
        'methodname'    => 'get_contacts',
        'description'   => 'List contact submissions for the Modern Commerce admin screens.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcontacts',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_contact' => [
        'classname'     => 'local_moderncommerce\external\contacts\admin',
        'methodname'    => 'get_contact',
        'description'   => 'Get one contact submission with its conversation thread.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:viewcontacts',
        'loginrequired' => true,
    ],
    'local_moderncommerce_reply_to_contact' => [
        'classname'     => 'local_moderncommerce\external\contacts\admin',
        'methodname'    => 'reply_to_contact',
        'description'   => 'Reply to a contact submission and email the sender.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecontacts',
        'loginrequired' => true,
    ],
    'local_moderncommerce_set_contact_status' => [
        'classname'     => 'local_moderncommerce\external\contacts\admin',
        'methodname'    => 'set_contact_status',
        'description'   => 'Update a contact submission status.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managecontacts',
        'loginrequired' => true,
    ],
    'local_moderncommerce_get_contact_email_settings' => [
        'classname'     => 'local_moderncommerce\external\contacts\admin',
        'methodname'    => 'get_email_settings',
        'description'   => 'Get contact email (autoreply/admin notification) configuration.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managesettings',
        'loginrequired' => true,
    ],
    'local_moderncommerce_save_contact_email_settings' => [
        'classname'     => 'local_moderncommerce\external\contacts\admin',
        'methodname'    => 'save_email_settings',
        'description'   => 'Save contact email configuration.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managesettings',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_get_branding' => [
        'classname'     => 'local_moderncommerce\external\branding\get_branding',
        'methodname'    => 'execute',
        'description'   => 'Get the Modern Commerce branding fields.',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managesettings',
        'loginrequired' => true,
    ],
    'local_moderncommerce_admin_save_branding' => [
        'classname'     => 'local_moderncommerce\external\branding\save_branding',
        'methodname'    => 'execute',
        'description'   => 'Validate and save the Modern Commerce branding fields.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => 'local/moderncommerce:managesettings',
        'loginrequired' => true,
    ],

    // Subscription subsystem absorbed from local_modernsubscription.
    'local_moderncommerce_subscription_get_overview' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'get_overview',
        'description' => 'Get subscription plan summary data for Modern Commerce React admin screens.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionplans',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_save_plan' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'save_plan',
        'description' => 'Create or update a subscription plan.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionplans',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_delete_plan' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'delete_plan',
        'description' => 'Delete a subscription plan.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionplans',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_get_feature_matrix' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'get_feature_matrix',
        'description' => 'Get subscription feature matrix data.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionfeatures',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_save_feature' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'save_feature',
        'description' => 'Create or update a subscription master feature.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionfeatures',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_delete_feature' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'delete_feature',
        'description' => 'Delete a subscription master feature.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionfeatures',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_save_feature_matrix' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'save_feature_matrix',
        'description' => 'Save subscription plan-feature mappings.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionfeatures',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_list_subscriptions' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'list_subscriptions',
        'description' => 'List user subscriptions for Modern Commerce React admin screens.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:viewsubscribers',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_get_subscription' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'get_subscription',
        'description' => 'Get one subscription detail record.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:viewsubscribers',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_subscription_action' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'subscription_action',
        'description' => 'Run a subscription lifecycle action.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptions',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_list_keys' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'list_keys',
        'description' => 'List subscription enrolment keys.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionplans',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_generate_keys' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'generate_keys',
        'description' => 'Generate subscription enrolment keys.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionplans',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_key_action' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'key_action',
        'description' => 'Update or delete a subscription enrolment key.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionplans',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_list_email_templates' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'list_email_templates',
        'description' => 'List subscription email template configuration.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionplans',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_save_email_template' => [
        'classname' => 'local_moderncommerce\subscription\external\admin_external',
        'methodname' => 'save_email_template',
        'description' => 'Save subscription email template configuration.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionplans',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_get_plan_access' => [
        'classname' => 'local_moderncommerce\subscription\external\access_external',
        'methodname' => 'get_plan_access',
        'description' => 'Get a subscription plan\'s access rules plus category and bundle pickers.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionplans',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_add_plan_access' => [
        'classname' => 'local_moderncommerce\subscription\external\access_external',
        'methodname' => 'add_plan_access',
        'description' => 'Add a course, category, or bundle access rule to a subscription plan.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionplans',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_remove_plan_access' => [
        'classname' => 'local_moderncommerce\subscription\external\access_external',
        'methodname' => 'remove_plan_access',
        'description' => 'Remove an access rule from a subscription plan.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionplans',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_save_plan_features' => [
        'classname' => 'local_moderncommerce\subscription\external\access_external',
        'methodname' => 'save_plan_features',
        'description' => 'Set the master features enabled for a subscription plan.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:managesubscriptionplans',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_get_plans' => [
        'classname' => 'local_moderncommerce\subscription\external\subscribe_external',
        'methodname' => 'get_plans',
        'description' => 'List active subscription plans plus the buyer\'s current subscription.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:subscribetoplan',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_subscribe' => [
        'classname' => 'local_moderncommerce\subscription\external\subscribe_external',
        'methodname' => 'subscribe',
        'description' => 'Subscribe to a plan (activate free/trial immediately, or return a checkout URL for paid plans).',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:subscribetoplan',
        'loginrequired' => true,
    ],
    'local_moderncommerce_subscription_redeem_key' => [
        'classname' => 'local_moderncommerce\subscription\external\subscribe_external',
        'methodname' => 'redeem_key',
        'description' => 'Redeem a pre-paid subscription key to activate a plan.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/moderncommerce:subscribetoplan',
        'loginrequired' => true,
    ],
];

$services = [
    'Modern Commerce services' => [
        'functions' => [
            'local_moderncommerce_get_catalog',
            'local_moderncommerce_get_bundle_details',
            'local_moderncommerce_get_course_details',
            'local_moderncommerce_reviews_get_overview',
            'local_moderncommerce_reviews_list_courses',
            'local_moderncommerce_reviews_list_reviews',
            'local_moderncommerce_reviews_moderate',
            'local_moderncommerce_get_course_reviews',
            'local_moderncommerce_submit_course_review',
            'local_moderncommerce_set_course_review_reaction',
            'local_moderncommerce_get_cart',
            'local_moderncommerce_get_cart_dropdown',
            'local_moderncommerce_update_cart',
            'local_moderncommerce_start_checkout',
            'local_moderncommerce_place_order',
            'local_moderncommerce_get_learner_dashboard',
            'local_moderncommerce_list_learner_courses',
            'local_moderncommerce_list_learner_certificates',
            'local_moderncommerce_list_learner_grades',
            'local_moderncommerce_list_learner_orders',
            'local_moderncommerce_get_learner_order',
            'local_moderncommerce_cancel_learner_order',
            'local_moderncommerce_list_learner_wishlist',
            'local_moderncommerce_update_learner_wishlist',
            'local_moderncommerce_get_learner_subscription',
            'local_moderncommerce_get_learner_subscription_access',
            'local_moderncommerce_get_learner_product_access',
            'local_moderncommerce_get_learner_profile',
            'local_moderncommerce_save_learner_profile',
            'local_moderncommerce_save_learner_profile_picture',
            'local_moderncommerce_search_courses',
            'local_moderncommerce_list_products',
            'local_moderncommerce_save_product',
            'local_moderncommerce_list_categories',
            'local_moderncommerce_save_category',
            'local_moderncommerce_delete_category',
            'local_moderncommerce_reorder_categories',
            'local_moderncommerce_get_product',
            'local_moderncommerce_toggle_product',
            'local_moderncommerce_archive_product',
            'local_moderncommerce_list_product_prices',
            'local_moderncommerce_save_product_price',
            'local_moderncommerce_archive_product_price',
            'local_moderncommerce_list_coupons',
            'local_moderncommerce_save_coupon',
            'local_moderncommerce_check_coupon_code',
            'local_moderncommerce_archive_coupon',
            'local_moderncommerce_list_coupon_targets',
            'local_moderncommerce_save_coupon_target',
            'local_moderncommerce_delete_coupon_target',
            'local_moderncommerce_search_coupon_target_options',
            'local_moderncommerce_admin_list_orders',
            'local_moderncommerce_admin_get_order',
            'local_moderncommerce_admin_update_order_status',
            'local_moderncommerce_admin_create_refund',
            'local_moderncommerce_admin_list_gateways',
            'local_moderncommerce_admin_save_gateway',
            'local_moderncommerce_admin_get_webhooks',
            'local_moderncommerce_admin_list_webhook_events',
            'local_moderncommerce_admin_list_bundles',
            'local_moderncommerce_admin_get_bundle',
            'local_moderncommerce_admin_save_bundle',
            'local_moderncommerce_admin_archive_bundle',
            'local_moderncommerce_admin_save_bundle_image',
            'local_moderncommerce_admin_list_keys',
            'local_moderncommerce_admin_generate_keys',
            'local_moderncommerce_admin_set_key_status',
            'local_moderncommerce_admin_list_invoices',
            'local_moderncommerce_admin_get_invoice',
            'local_moderncommerce_admin_save_invoice',
            'local_moderncommerce_admin_set_invoice_status',
            'local_moderncommerce_admin_search_customers',
            'local_moderncommerce_admin_get_report',
            'local_moderncommerce_admin_get_dashboard',
            'local_moderncommerce_admin_get_dashboard_charts',
            'local_moderncommerce_admin_get_dashboard_layout',
            'local_moderncommerce_admin_save_dashboard_layout',
            'local_moderncommerce_get_storefront_page',
            'local_moderncommerce_get_storefront_gallery',
            'local_moderncommerce_get_demo_catalog',
            'local_moderncommerce_list_widget_presets',
            'local_moderncommerce_save_widget_preset',
            'local_moderncommerce_delete_widget_preset',
            'local_moderncommerce_newsletter_subscribe',
            'local_moderncommerce_newsletter_list_subscribers',
            'local_moderncommerce_newsletter_delete_subscriber',
            'local_moderncommerce_newsletter_export_subscribers',
            'local_moderncommerce_get_storefront_layout',
            'local_moderncommerce_save_storefront_layout',
            'local_moderncommerce_toggle_storefront_page',
            'local_moderncommerce_get_storefront_widget',
            'local_moderncommerce_save_storefront_widget',
            'local_moderncommerce_add_storefront_widget',
            'local_moderncommerce_delete_storefront_widget',
            'local_moderncommerce_upload_slide_image',
            'local_moderncommerce_validate_key',
            'local_moderncommerce_redeem_key',
            'local_moderncommerce_admin_list_emails',
            'local_moderncommerce_admin_get_email',
            'local_moderncommerce_admin_save_email',
            'local_moderncommerce_email_get_metadata',
            'local_moderncommerce_email_list_templates',
            'local_moderncommerce_email_get_template',
            'local_moderncommerce_email_save_template',
            'local_moderncommerce_email_delete_template',
            'local_moderncommerce_email_clone_template',
            'local_moderncommerce_email_preview_template',
            'local_moderncommerce_email_get_shell',
            'local_moderncommerce_email_save_shell',
            'local_moderncommerce_email_preview_shell',
            'local_moderncommerce_email_reset_shell',
            'local_moderncommerce_admin_list_payment_events',
            'local_moderncommerce_admin_list_webhook_ledger',
            'local_moderncommerce_admin_list_audit_log',
            'local_moderncommerce_admin_get_course_features',
            'local_moderncommerce_admin_save_course_features',
            'local_moderncommerce_admin_get_bundle_features',
            'local_moderncommerce_admin_save_bundle_features',
            'local_moderncommerce_admin_get_settings',
            'local_moderncommerce_admin_save_settings',
            'local_moderncommerce_admin_get_notifications',
            'local_moderncommerce_admin_save_notification_settings',
            'local_moderncommerce_submit_contact',
            'local_moderncommerce_get_contacts',
            'local_moderncommerce_get_contact',
            'local_moderncommerce_reply_to_contact',
            'local_moderncommerce_set_contact_status',
            'local_moderncommerce_get_contact_email_settings',
            'local_moderncommerce_save_contact_email_settings',
            'local_moderncommerce_admin_get_branding',
            'local_moderncommerce_admin_save_branding',
            'local_moderncommerce_admin_list_customers',
            'local_moderncommerce_admin_get_customer',
            'local_moderncommerce_admin_list_wishlists',
            'local_moderncommerce_subscription_get_overview',
            'local_moderncommerce_subscription_save_plan',
            'local_moderncommerce_subscription_delete_plan',
            'local_moderncommerce_subscription_get_feature_matrix',
            'local_moderncommerce_subscription_save_feature',
            'local_moderncommerce_subscription_delete_feature',
            'local_moderncommerce_subscription_save_feature_matrix',
            'local_moderncommerce_subscription_list_subscriptions',
            'local_moderncommerce_subscription_get_subscription',
            'local_moderncommerce_subscription_subscription_action',
            'local_moderncommerce_subscription_list_keys',
            'local_moderncommerce_subscription_generate_keys',
            'local_moderncommerce_subscription_key_action',
            'local_moderncommerce_subscription_list_email_templates',
            'local_moderncommerce_subscription_save_email_template',
            'local_moderncommerce_subscription_get_plan_access',
            'local_moderncommerce_subscription_add_plan_access',
            'local_moderncommerce_subscription_remove_plan_access',
            'local_moderncommerce_subscription_save_plan_features',
            'local_moderncommerce_subscription_get_plans',
            'local_moderncommerce_subscription_subscribe',
            'local_moderncommerce_subscription_redeem_key',
        ],
        'restrictedusers' => 0,
        'enabled' => 1,
    ],
];
